let data=null, chapter=0, qi=0, selected=null, submitted=false, mode='practice', filter='all', query='', exam=null, examTimer=null;
const state=JSON.parse(localStorage.getItem('neetq_state')||'{}');
state.attempts ||= {}; state.bookmarks ||= {}; state.settings ||= {};
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=(ci,qi)=>`${data.subject}|${ci}|${qi}`;
function save(){localStorage.setItem('neetq_state',JSON.stringify(state))}
function allQs(){return data.chapters.flatMap((c,ci)=>c.questions.map((q,i)=>({...q,_ci:ci,_qi:i,_chapter:c.title,_key:key(ci,i)})))}
function qs(){const base=data.chapters[chapter]?.questions||[]; return base.filter((q,i)=>{const k=key(chapter,i), a=state.attempts[k]; if(filter==='unattempted'&&a)return false; if(filter==='incorrect'&&(!a||a.correct))return false; if(filter==='bookmarked'&&!state.bookmarks[k])return false; if(query&&!(`${q.question} ${q.options.map(o=>o.text).join(' ')}`).toLowerCase().includes(query.toLowerCase()))return false; return true})}
function stats(){const a=Object.values(state.attempts), attempted=a.length, correct=a.filter(x=>x.correct).length; return {attempted,correct,accuracy:attempted?Math.round(correct/attempted*100):0,bookmarks:Object.keys(state.bookmarks).length}}
function render(){if(!data)return; if(mode==='exam'){renderExam();return} const list=qs(); if(qi>=list.length)qi=Math.max(0,list.length-1); const q=list[qi]; const s=stats();
app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">NEET-PG <em>QBank</em></div><input class="side-search" id="chapterSearch" placeholder="Search chapters…"><div class="section-label">${esc(data.subject)} · ${data.chapters.length} lessons</div><div id="chapters">${data.chapters.map((c,i)=>`<button class="chapter ${i===chapter?'active':''}" data-i="${i}">${esc(c.number+'. '+c.title)}<small>${c.questions.length}</small></button>`).join('')}</div></aside><main class="main"><div class="topbar"><div><div class="eyebrow">${esc(data.subject)} · ${esc(data.chapters[chapter]?.title||'')}</div><h1>${mode==='exam'?'Exam Mode':'Question Practice'}</h1></div><div class="top-actions"><button class="btn" id="examBtn">Timed Exam</button><label class="btn">Import PDF<input id="upload" type="file" accept="application/pdf" hidden></label></div></div><div class="dashboard"><div class="card metric"><span>Attempted</span><b>${s.attempted}</b></div><div class="card metric"><span>Correct</span><b>${s.correct}</b></div><div class="card metric"><span>Accuracy</span><b>${s.accuracy}%</b></div><div class="card metric"><span>Bookmarked</span><b>${s.bookmarks}</b></div></div><div class="modebar"><button class="btn ${filter==='all'?'primary':''}" data-filter="all">All</button><button class="btn ${filter==='unattempted'?'primary':''}" data-filter="unattempted">Unattempted</button><button class="btn ${filter==='incorrect'?'primary':''}" data-filter="incorrect">Incorrect</button><button class="btn ${filter==='bookmarked'?'primary':''}" data-filter="bookmarked">Bookmarks</button><input class="text" id="questionSearch" style="max-width:300px" placeholder="Search this chapter…" value="${esc(query)}"></div><div class="workspace"><section class="card question-card">${q?questionHTML(q,list.length):'<div class="empty"><h3>No questions match this filter.</h3><p>Try another filter or clear the search.</p></div>'}</section><aside class="card sidepanel"><div class="eyebrow">Chapter progress</div><div class="statrow"><span>Current</span><b>${list.length?qi+1:0} / ${list.length}</b></div><div class="progress"><i style="width:${list.length?((qi+1)/list.length*100):0}%"></i></div><div class="notice">Answers and explanations are taken from the uploaded Qbank. The explanation is shown after <b>every</b> submission, including correct answers.</div><div class="filters"><select class="select" id="chapterSelect">${data.chapters.map((c,i)=>`<option value="${i}" ${i===chapter?'selected':''}>${esc(c.number+'. '+c.title)}</option>`).join('')}</select></div><div class="eyebrow" style="margin-top:18px">Question palette</div><div class="palette">${list.map((x,i)=>{const a=state.attempts[x._key];return `<button class="pbtn ${i===qi?'current ':''}${a?'done ':''}${a&&!a.correct?'incorrect':''}" data-q="${i}">${i+1}</button>`}).join('')}</div></aside></div></main></div>`;
wire(list,q);}
function questionHTML(q,total){const bookmarked=!!state.bookmarks[q._key]; return `<div class="qmeta"><span><span class="pill">${esc(data.chapters[chapter].title)}</span> · Q ${qi+1} / ${total}</span><button class="btn bookmark ${bookmarked?'active':''}" id="bookmark">${bookmarked?'★ Bookmarked':'☆ Bookmark'}</button></div><div class="qtext">${esc(q.question)}</div>${q.source_page?`<div class="media"><img loading="lazy" src="/api/source-page/${q.source_page}.png" alt="Source page ${q.source_page}"><div class="caption">Source page ${q.source_page} from uploaded Qbank</div></div>`:''}<div class="options">${q.options.map(o=>{let cls='option';if(selected===o.label&&!submitted)cls+=' selected';if(submitted&&o.label===q.correct_answer)cls+=' correct';if(submitted&&selected===o.label&&selected!==q.correct_answer)cls+=' wrong';return `<button class="${cls}" data-label="${esc(o.label)}" ${submitted?'disabled':''}><span class="letter">${esc(o.label)}</span><span>${esc(o.text)}</span></button>`}).join('')}</div>${submitted?`<div class="result ${selected===q.correct_answer?'good':'bad'}">${selected===q.correct_answer?'✓ Correct':'✕ Incorrect'}${selected!==q.correct_answer&&q.correct_answer?` · Correct answer: ${esc(q.correct_answer)}`:''}</div><div class="explanation"><h3>📖 Explanation</h3><div class="explanation-body">${esc(stripAnswer(q.explanation))}</div></div>`:''}<div class="actions"><button class="btn" id="prev" ${qi===0?'disabled':''}>← Previous</button>${submitted?'<button class="btn primary" id="next">Next →</button>':'<button class="btn primary" id="submit" '+(!selected?'disabled':'')+'>Submit Answer</button>'}</div>`}
function stripAnswer(x){return String(x||'').replace(/^Correct Answer:.*?\nExplanation:\s*/i,'').trim()}
function wire(list,q){
 document.querySelectorAll('.chapter').forEach(b=>b.onclick=()=>{chapter=+b.dataset.i;qi=0;selected=null;submitted=false;query='';render()});
 document.getElementById('chapterSearch').oninput=e=>{const x=e.target.value.toLowerCase();document.querySelectorAll('.chapter').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(x)?'flex':'none')};
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;qi=0;selected=null;submitted=false;render()});
 document.getElementById('questionSearch').onchange=e=>{query=e.target.value;qi=0;selected=null;submitted=false;render()};
 document.getElementById('chapterSelect').onchange=e=>{chapter=+e.target.value;qi=0;selected=null;submitted=false;filter='all';query='';render()};
 document.querySelectorAll('.pbtn').forEach(b=>b.onclick=()=>{qi=+b.dataset.q;selected=null;submitted=false;render()});
 document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{if(!submitted){selected=b.dataset.label;render()}});
 const sub=document.getElementById('submit'); if(sub)sub.onclick=()=>{if(!selected)return;submitted=true;state.attempts[q._key]={correct:selected===q.correct_answer,selected,ts:Date.now()};save();render()};
 const next=document.getElementById('next');if(next)next.onclick=()=>{if(qi<list.length-1){qi++;selected=null;submitted=false;render()}};
 const prev=document.getElementById('prev');if(prev)prev.onclick=()=>{if(qi>0){qi--;selected=null;submitted=false;render()}};
 const bm=document.getElementById('bookmark');if(bm)bm.onclick=()=>{if(state.bookmarks[q._key])delete state.bookmarks[q._key];else state.bookmarks[q._key]=true;save();render()};
 document.getElementById('upload').onchange=upload; document.getElementById('examBtn').onclick=()=>examModal();
}
function examModal(){app.insertAdjacentHTML('beforeend',`<div class="exam-overlay" id="exam"><div class="exam-modal"><h2>Start timed exam</h2><p class="notice">Random questions from the entire ${esc(data.subject)} Qbank. You will receive the explanation after submitting each answer, including correct answers.</p><div class="exam-grid" style="margin-top:14px"><label>Questions<select class="select" id="examN"><option>20</option><option>50</option><option>100</option></select></label><label>Minutes<select class="select" id="examT"><option>20</option><option>45</option><option>90</option><option>180</option></select></label></div><div class="actions"><button class="btn" id="cancelExam">Cancel</button><button class="btn primary" id="startExam">Start Exam</button></div></div></div>`);document.getElementById('cancelExam').onclick=()=>document.getElementById('exam').remove();document.getElementById('startExam').onclick=()=>{const n=Math.min(+document.getElementById('examN').value,allQs().length), mins=+document.getElementById('examT').value;const pool=allQs().sort(()=>Math.random()-.5).slice(0,n);exam={questions:pool,index:0,selected:null,submitted:false,answers:{},score:0,total:n,seconds:mins*60,finished:false};mode='exam';document.getElementById('exam').remove();startExamTimer();render()}}
function startExamTimer(){clearInterval(examTimer);examTimer=setInterval(()=>{if(!exam||exam.finished){clearInterval(examTimer);return}exam.seconds--;if(exam.seconds<=0){finishExam();}else{const t=document.getElementById('examClock');if(t)t.textContent=formatTime(exam.seconds)}},1000)}
function formatTime(sec){const m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function renderExam(){const q=exam.questions[exam.index], total=exam.total;app.innerHTML=`<div class="main" style="max-width:1100px"><div class="topbar"><div><div class="eyebrow">${esc(data.subject)} · Timed Exam</div><h1>Exam Mode</h1></div><div class="top-actions"><div class="btn" id="examClock">${formatTime(exam.seconds)}</div><button class="btn danger" id="finishExam">Finish Exam</button></div></div><div class="workspace"><section class="card question-card">${examQuestionHTML(q,total)}</section><aside class="card sidepanel"><div class="eyebrow">Exam progress</div><div class="statrow"><span>Question</span><b>${exam.index+1} / ${total}</b></div><div class="progress"><i style="width:${((exam.index+1)/total)*100}%"></i></div><div class="eyebrow" style="margin-top:18px">Palette</div><div class="palette">${exam.questions.map((x,i)=>`<button class="pbtn ${i===exam.index?'current ':''}${exam.answers[x._key]?'done':''}" data-eq="${i}">${i+1}</button>`).join('')}</div><div class="notice" style="margin-top:16px">Scoring: +4 for correct, −1 for incorrect, 0 for unattempted.</div></aside></div></div>`;document.querySelectorAll('[data-eq]').forEach(b=>b.onclick=()=>{if(!exam.submitted){exam.index=+b.dataset.eq;exam.selected=null}render()});document.querySelectorAll('.exam-option').forEach(b=>b.onclick=()=>{if(!exam.submitted){exam.selected=b.dataset.label;render()}});const sub=document.getElementById('examSubmit');if(sub)sub.onclick=()=>{if(!exam.selected)return;exam.submitted=true;exam.answers[q._key]={selected:exam.selected,correct:exam.selected===q.correct_answer};exam.score+=exam.selected===q.correct_answer?4:-1;render()};const next=document.getElementById('examNext');if(next)next.onclick=()=>{if(exam.index<total-1){exam.index++;exam.selected=null;exam.submitted=false;render()}else finishExam()};document.getElementById('finishExam').onclick=finishExam}
function examQuestionHTML(q,total){return `<div class="qmeta"><span><span class="pill">${esc(q._chapter)}</span> · Q ${exam.index+1} / ${total}</span></div><div class="qtext">${esc(q.question)}</div>${q.source_page?`<div class="media"><img loading="lazy" src="/api/source-page/${q.source_page}.png" alt="Source page ${q.source_page}"><div class="caption">Source page ${q.source_page}</div></div>`:''}<div class="options">${q.options.map(o=>{let cls='option exam-option';if(exam.selected===o.label&&!exam.submitted)cls+=' selected';if(exam.submitted&&o.label===q.correct_answer)cls+=' correct';if(exam.submitted&&exam.selected===o.label&&exam.selected!==q.correct_answer)cls+=' wrong';return `<button class="${cls}" data-label="${esc(o.label)}" ${exam.submitted?'disabled':''}><span class="letter">${esc(o.label)}</span><span>${esc(o.text)}</span></button>`}).join('')}</div>${exam.submitted?`<div class="result ${exam.selected===q.correct_answer?'good':'bad'}">${exam.selected===q.correct_answer?'✓ Correct':'✕ Incorrect'}${exam.selected!==q.correct_answer?` · Correct answer: ${esc(q.correct_answer)}`:''}</div><div class="explanation"><h3>📖 Explanation</h3><div class="explanation-body">${esc(stripAnswer(q.explanation))}</div></div>`:''}<div class="actions">${exam.submitted&&exam.index===0?'<span></span>':'<button class="btn" id="examPrev" '+(exam.index===0?'disabled':'')+'>← Previous</button>'}${exam.submitted?'<button class="btn primary" id="examNext">'+(exam.index===total-1?'Finish':'Next →')+'</button>':'<button class="btn primary" id="examSubmit" '+(!exam.selected?'disabled':'')+'>Submit Answer</button>'}</div>`}
function finishExam(){if(!exam)return;clearInterval(examTimer);exam.finished=true;const answered=Object.values(exam.answers),correct=answered.filter(x=>x.correct).length,wrong=answered.filter(x=>!x.correct).length,unattempted=exam.total-answered.length;app.innerHTML=`<div class="main" style="max-width:900px"><div class="card" style="padding:28px;text-align:center"><div class="eyebrow">${esc(data.subject)} · Exam complete</div><h1>Exam Result</h1><div class="dashboard" style="margin-top:20px"><div class="card metric"><span>Score</span><b>${correct*4-wrong}</b></div><div class="card metric"><span>Correct</span><b>${correct}</b></div><div class="card metric"><span>Incorrect</span><b>${wrong}</b></div><div class="card metric"><span>Unattempted</span><b>${unattempted}</b></div></div><div class="actions"><button class="btn primary" id="backPractice">Back to Practice</button></div></div></div>`;document.getElementById('backPractice').onclick=()=>{mode='practice';chapter=0;qi=0;selected=null;submitted=false;render()}}
async function upload(e){const f=e.target.files[0];if(!f)return;const fd=new FormData();fd.append('file',f);document.querySelector('.main').style.opacity='.5';try{const r=await fetch('/api/upload',{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());data=await r.json();chapter=0;qi=0;selected=null;submitted=false;filter='all';query='';state.attempts={};state.bookmarks={};save();render()}catch(err){alert(err.message)}finally{document.querySelector('.main').style.opacity='1'}}
async function load(){try{const r=await fetch('/api/qbank');if(!r.ok)throw new Error('Qbank unavailable');data=await r.json();render()}catch(e){app.innerHTML='<div class="empty"><h2>Could not load Qbank</h2><p>Start the FastAPI server and open the site again.</p></div>'}}
load();
